### ISSUE TITLE
No state UP

### ISSUE THREAD

**Issue by carlozleite** [andrefreitas/rocketchat-nagios#6]
Traceback (most recent call last):
  File "/usr/lib64/nagios/plugins/rocketchat.py", line 109, in <module>
    data = create_data(args, CONFIG)
  File "/usr/lib64/nagios/plugins/rocketchat.py", line 80, in create_data
    color = config["colors"][state]
KeyError: 'UP'

Solve:

CONFIG = {
    "avatar": "https://raw.githubusercontent.com/andrefreitas/rocketchat-nagios/master/images/nagios_128.png", #noqa
    "alias": "Nagios",
    "colors": {
        "OK": "#36a64f",
        "CRITICAL": "#d00000",
        "WARNING": "#daa038",
        "UNKNOWN": "#e3e4e6",
        "DOWN": "#d00000",
        "UP":   "#40b207", <--------
        "UNKNOWN": "#e3e4e6",
        "UNREACHABLE": "#e3e4e6"
    }

**Comment by andrefreitas** [comment]
Hi, thanks for noticing this bug! Can you submit a PR?

**Comment by andrefreitas** [comment]
I have just fixed this with 77cbd6c
