### ISSUE TITLE
Notifications not showing content

### ISSUE THREAD

**Issue by karlettoh** [andrefreitas/rocketchat-nagios#7]
OS - Mint
RC Client - https://github.com/RocketChat/Rocket.Chat.Electron/releases/download/2.9.0/rocketchat_2.9.0_amd64.deb

Issue: Notifications to the desktop are not showing the actual content of the nagios alert. The channel contains the full information though.

Screengrab: 
![image](https://user-images.githubusercontent.com/33254846/32223302-b462f864-be34-11e7-9fa8-ca748b9bf2ca.png)

**Comment by karlettoh** [comment]
To note: The behaviour is the same on our Window's clients, too.

**Comment by andrefreitas** [comment]
Hi, I believe I forgot to answer this. What version of Rocket Chat Server are you running?

**Comment by PitoneMaledetto** [comment]
Hi all,
if the service description has a space in it the link is broken:
See http://my-nagios/nagios/cgi-bin/extinfo.cgi?type=2&host=pr-ze-sys-gw-01&service=Live Service

I have tried:
def encode_special_characters(text):
    text = text.replace("%", "%25")
    text = text.replace("&", "%26")
    text = text.replace(" ", "%20")
    return text

but for some reason it did not work.

Moreover the notification still coming through as Nagios: Uploaded a file.

Thanks

**Comment by andrefreitas** [comment]
@PitoneMaledetto thanks for adding more information. I need to book time to debug this.

**Comment by rvdo** [comment]
Hi Andre and all,
Due to special chars in our nagios output, I needed to patch rocketchat.py to make it work : 
```
# diff rocketchat.py rocketchat.py.orig
69c69
<     return text.decode('iso-8859-1').encode('utf8')
---
>     return text
```

> Nagios @rocket.cat Bot 13:30
> webapp10/Application AIDOP2 is CRITICAL:
> RACVISION CRITICAL - HTTP error: 500 Internal Server Error (Cant connect to webapp10.in.ac-caen.fr:14002 (connect: Connexion refusée))

Because of character **é** in _refusée_ it didn't work with original version
Hope this helps

**Comment by andrefreitas** [comment]
Hello @rvdo first of all thanks for your help.

I was not able to reproduce your issue with "refusée":

```
./rocketchat.py \
        --url http://localhost:32768/hooks/9rCxq5C7EDZnbcspc/**************** \
        --hostalias alfredo \
        --notificationtype RECOVERY \
        --servicestate UNKNOWN \
        --serviceoutput "Refusée" \
        --servicedesc counter
{"success":true}
```

<img width="422" alt="rocketchat-screenshot" src="https://user-images.githubusercontent.com/1192089/52674757-8052a380-2f1c-11e9-95f7-bf0e5771d4cc.png">

Can you please give me more details on the scenario you found the issue? I believe the problem maybe before invoking the script.

**Comment by rvdo** [comment]
Hi Andre
Alert was sent by check_mk/nagios. 
One check failed because of service unavailability. We tuned our check_mk/nagios not to use proxy. If we use the proxy, no french chars and everything is ok. Without the proxy, maybe because of locale settings, the check response contains an accent : 
```
[root@racvision3 ~]# http_proxy='' wget http://webapp10.in.ac-caen.fr:14002/aidop/racvision
--2019-02-07 13:28:25--  http://webapp10.in.ac-caen.fr:14002/aidop/racvision
Résolution de webapp10.in.ac-caen.fr... 172.xxx.yyy.zzz
Connexion vers webapp10.in.ac-caen.fr|172.xxx.yyy.zzz|:14002...échec: Connexion refusée.
[root@racvision3 ~]# wget http://webapp10.in.ac-caen.fr:14002/aidop/racvision
--2019-02-07 13:28:31--  http://webapp10.in.ac-caen.fr:14002/aidop/racvision
Résolution de proxy.in.ac-caen.fr... 192.xxx.yyy.zzz
Connexion vers proxy.in.ac-caen.fr|192.xxx.yyy.zzz|:8080...connecté.
requête Proxy transmise, en attente de la réponse...503 Service Unavailable
2019-02-07 13:28:31 ERREUR 503: Service Unavailable.
```
Except for the patch, everything was made according to your tuto

**Comment by andrefreitas** [comment]
@rvdo I need more instructions to reproduce your issue. I am lacking context of check_mk/nagios.

**Comment by rvdo** [comment]
Andre,

I can't actually explain how check_mk/nagios is installed on our infra because I am just a user.
Nevertheless, the issue appears even in CLI : 
With original rocketchat.py : 
```
[root@racvision3 ~]# /usr/local/nagios/libexec-caen/rocketchat.py --url http://rocketchat.app.in.ac-caen.fr/hooks/y5...xh --hostalias "webapp10" --notificationtype "Application AIDOP2" --servicestate "CRITICAL"  --serviceoutput "RACVISION CRITICAL - HTTP error: 500 Internal Server Error (Can't connect to webapp10.in.ac-caen.fr:14002 (connect: Connexion refusée))"
Traceback (most recent call last):
  File "/usr/local/nagios/libexec-caen/rocketchat.py", line 113, in <module>
    data = create_data(args, CONFIG)
  File "/usr/local/nagios/libexec-caen/rocketchat.py", line 97, in create_data
    data = "payload=" + json.dumps(payload)
  File "/usr/lib64/python2.6/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.6/json/encoder.py", line 367, in encode
    chunks = list(self.iterencode(o))
  File "/usr/lib64/python2.6/json/encoder.py", line 309, in _iterencode
    for chunk in self._iterencode_dict(o, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 275, in _iterencode_dict
    for chunk in self._iterencode(value, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 306, in _iterencode
    for chunk in self._iterencode_list(o, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 204, in _iterencode_list
    for chunk in self._iterencode(value, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 309, in _iterencode
    for chunk in self._iterencode_dict(o, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 275, in _iterencode_dict
    for chunk in self._iterencode(value, markers):
  File "/usr/lib64/python2.6/json/encoder.py", line 294, in _iterencode
    yield encoder(o)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 158: invalid continuation byte
```
Converting message in UTF-8 makes it work : 
```
[root@racvision3 ~]# /usr/local/nagios/libexec-caen/rocketchat.py --url http://rocketchat.app.in.ac-caen.fr/hooks/y5...xh --hostalias "webapp10" --notificationtype "Application AIDOP2" --servicestate "CRITICAL"  --serviceoutput "$(echo "RACVISION CRITICAL - HTTP error: 500 Internal Server Error (Can't connect to webapp10.in.ac-caen.fr:14002 (connect: Connexion refusée))" | iconv -t UTF-8)"
{"success":true}
```
Maybe there's a need to check somewhere environment to convert message if needed ?

Regards

**Comment by conxuro** [comment]
I had the same problem with desktop notifications (not the message itself in the app), and is possibly due to Rocket hook API, that doesn't show attachment text but "uploaded a file".

The workaround I do for the moment is to omit the attachment section and write the message in the body text field, i.e.:
```
    payload = {
        "alias": config["alias"],
        "avatar": config["avatar"],
        "text":text
#       "attachments": [
#            {
#                "text": text,
#                "color": color
#            }
#        ]
    }
```
We loose the color but we get the text in the notification.

**Comment by andrefreitas** [comment]
It seems like when the content payload contains some "not normal" characters, we need to encoded them. Can you share your payload @conxuro ?

**Comment by conxuro** [comment]
I think the character encode issue is not related to the notifications issue.

With this payload, that has no special characters, is still showing "uploaded a file" instead of "TEST" in the desktop notification:
```
    payload = {
        "alias": config["alias"],
        "avatar": config["avatar"],
        "attachments": [
            {
                "text": "TEST",
                "color": color
            }
        ]
    }
```
The problem is that the attachments section is shown in the desktop notification always as "uploaded a file" instead of the content, but this seems to be an issue from Rocketchat not from rocketchat-nagios plugin.

**Comment by andrefreitas** [comment]
Sure! Need to find a way to reproduce this. What version of RocketChat you have? I don't do an integration test for a couple of time.

**Comment by conxuro** [comment]
I'm using latest 2.3.0 release on Debian 9 connecting with Ubuntu 18.04 client version 2.15.5 and/or Firefox 70, both with the same behavior with the desktop notifications.

**Comment by andrefreitas** [comment]
Thanks! I will take a look a this when I have time. Thanks for the collaboration! 🙏

**Comment by andrefreitas** [comment]
Hi, I am archiving this project. I don't have time to keep updating it. Fork if you need to use it :) Thanks mates.
